<?php

namespace Database\Seeders;

use App\Models\Equipment;
use Illuminate\Database\Seeder;

class EquipmentSeeder extends Seeder
{
    public function run(): void
    {
        $equipment = [
            [
                'location'      => 'ICU - Room 101',
                'description'   => 'Patient Monitor',
                'brand'         => 'Philips',
                'model'         => 'IntelliVue MX450',
                'serial_number' => 'PH-MX450-00123',
                'tag_number'    => 'BIO-001',
                'pm_date_done'  => '2026-01-15',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'ICU - Room 102',
                'description'   => 'Patient Monitor',
                'brand'         => 'GE Healthcare',
                'model'         => 'CARESCAPE B650',
                'serial_number' => 'GE-B650-00456',
                'tag_number'    => 'BIO-002',
                'pm_date_done'  => '2026-01-20',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Operating Room 1',
                'description'   => 'Anesthesia Machine',
                'brand'         => 'Dräger',
                'model'         => 'Fabius GS Premium',
                'serial_number' => 'DR-FGSP-00789',
                'tag_number'    => 'BIO-003',
                'pm_date_done'  => '2025-12-10',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Operating Room 2',
                'description'   => 'Electrosurgical Unit',
                'brand'         => 'Medtronic',
                'model'         => 'Force FX-8C',
                'serial_number' => 'MD-FX8C-01122',
                'tag_number'    => 'BIO-004',
                'pm_date_done'  => '2025-11-05',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Emergency Room',
                'description'   => 'Defibrillator',
                'brand'         => 'Zoll',
                'model'         => 'R Series ALS',
                'serial_number' => 'ZL-RALS-00334',
                'tag_number'    => 'BIO-005',
                'pm_date_done'  => '2026-02-01',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Emergency Room',
                'description'   => 'Infusion Pump',
                'brand'         => 'Baxter',
                'model'         => 'Sigma Spectrum 6.05',
                'serial_number' => 'BX-SS605-00567',
                'tag_number'    => 'BIO-006',
                'pm_date_done'  => '2025-10-22',
                'calibration'   => 'Due for Calibration',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Radiology Department',
                'description'   => 'Ultrasound Machine',
                'brand'         => 'Siemens',
                'model'         => 'ACUSON Juniper',
                'serial_number' => 'SI-ACJ-00890',
                'tag_number'    => 'BIO-007',
                'pm_date_done'  => '2026-01-08',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Radiology Department',
                'description'   => 'X-Ray Machine',
                'brand'         => 'Canon Medical',
                'model'         => 'CXDI-Elite',
                'serial_number' => 'CM-CXE-01234',
                'tag_number'    => 'BIO-008',
                'pm_date_done'  => '2025-09-14',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Under Maintenance',
            ],
            [
                'location'      => 'Ward A - Nursing Station',
                'description'   => 'Syringe Pump',
                'brand'         => 'B. Braun',
                'model'         => 'Perfusor Space',
                'serial_number' => 'BB-PFS-01567',
                'tag_number'    => 'BIO-009',
                'pm_date_done'  => '2026-02-14',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Ward B - Nursing Station',
                'description'   => 'Syringe Pump',
                'brand'         => 'B. Braun',
                'model'         => 'Perfusor Space',
                'serial_number' => 'BB-PFS-01568',
                'tag_number'    => 'BIO-010',
                'pm_date_done'  => '2026-02-14',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Laboratory',
                'description'   => 'Hematology Analyzer',
                'brand'         => 'Sysmex',
                'model'         => 'XN-1000',
                'serial_number' => 'SX-XN1K-02345',
                'tag_number'    => 'BIO-011',
                'pm_date_done'  => '2025-12-28',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Laboratory',
                'description'   => 'Blood Chemistry Analyzer',
                'brand'         => 'Roche',
                'model'         => 'Cobas c 311',
                'serial_number' => 'RC-C311-02678',
                'tag_number'    => 'BIO-012',
                'pm_date_done'  => '2026-01-30',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'NICU',
                'description'   => 'Infant Incubator',
                'brand'         => 'Dräger',
                'model'         => 'Isolette C2000',
                'serial_number' => 'DR-IC2K-03001',
                'tag_number'    => 'BIO-013',
                'pm_date_done'  => '2026-03-01',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'NICU',
                'description'   => 'Phototherapy Unit',
                'brand'         => 'GE Healthcare',
                'model'         => 'Lullaby LED',
                'serial_number' => 'GE-LLD-03234',
                'tag_number'    => 'BIO-014',
                'pm_date_done'  => '2025-11-18',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Cardiology Department',
                'description'   => 'ECG Machine',
                'brand'         => 'Nihon Kohden',
                'model'         => 'Cardiofax G ECG-2350',
                'serial_number' => 'NK-2350-03456',
                'tag_number'    => 'BIO-015',
                'pm_date_done'  => '2025-08-20',
                'calibration'   => 'Due for Calibration',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Respiratory Therapy',
                'description'   => 'Mechanical Ventilator',
                'brand'         => 'Medtronic',
                'model'         => 'Puritan Bennett 980',
                'serial_number' => 'MD-PB980-03789',
                'tag_number'    => 'BIO-016',
                'pm_date_done'  => '2026-02-22',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Respiratory Therapy',
                'description'   => 'Pulse Oximeter',
                'brand'         => 'Masimo',
                'model'         => 'Radical-7',
                'serial_number' => 'MS-R7-04012',
                'tag_number'    => 'BIO-017',
                'pm_date_done'  => '2026-01-05',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Storage Room',
                'description'   => 'Portable Suction Machine',
                'brand'         => 'Medela',
                'model'         => 'Dominant 50',
                'serial_number' => 'ML-D50-04345',
                'tag_number'    => 'BIO-018',
                'pm_date_done'  => '2025-07-10',
                'calibration'   => 'Not Required',
                'status'        => 'For Repair',
            ],
            [
                'location'      => 'Ward C - Room 305',
                'description'   => 'Hospital Bed with Scale',
                'brand'         => 'Hill-Rom',
                'model'         => 'Centrella Smart+',
                'serial_number' => 'HR-CSP-04678',
                'tag_number'    => 'BIO-019',
                'pm_date_done'  => '2026-03-10',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
            [
                'location'      => 'Dialysis Unit',
                'description'   => 'Hemodialysis Machine',
                'brand'         => 'Fresenius',
                'model'         => '5008S CorDiax',
                'serial_number' => 'FR-5008S-05001',
                'tag_number'    => 'BIO-020',
                'pm_date_done'  => '2026-02-28',
                'calibration'   => 'Uncalibrated',
                'status'        => 'Functional',
            ],
        ];

        foreach ($equipment as $item) {
            Equipment::create($item);
        }

        // Generate 50 additional sample equipment records using factory
        Equipment::factory()
            ->count(50)
            ->create();
    }
}
